repos:
  - repo: https://github.com/psf/black
    rev: 21.5b1
    hooks:
      - id: black
        exclude: (.*/scripts/.*|.*/migrations/.*)$
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
    -   id: prettier
        name: Vue Prettier
        files: (app/.*\.vue|app/.*\.js)$
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.0
    hooks:
      - id: trailing-whitespace
        exclude: \.(css|ts|tsx|bck|csv)$
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: requirements-txt-fixer
      - id: debug-statements
      - id: check-added-large-files
        args: [--maxkb=550]
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
        exclude: (.*/scripts/.*|.*/migrations/.*)$
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
        args: [--format=txt, --quiet]
  - repo: https://github.com/PyCQA/prospector
    rev: 1.3.1
    hooks:
      - id: prospector
        language: system
        args: [--messages-only, --output-format=pylint]
        exclude: (.*/migrations/.*)$
