# Generated by Django 3.2.16 on 2023-01-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='location_meta',
            field=models.JSONField(default=dict),
        ),
    ]
