# Generated by Django 3.2.16 on 2023-01-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_location_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='location_meta',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
