# Generated by Django 3.2.16 on 2023-01-06 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_location_meta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='time_in',
            new_name='check_in',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='time_out',
            new_name='check_out',
        ),
    ]
